config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get 'register', to: 'registrations#new'
  post 'register', to: 'registrations#create'

  get 'chart', to: 'transactions#chart', as: 'transactions_chart'

  resources :users, only: [:new, :create, :index, :show]
  resources :wallets
  resources :categories
  resources :transactions
  resources :transaction_templates
  resources :passwords, only: %i[edit update], param: :token

  resource :reset_password, only: %i[new create]


  root "dashboard#index"
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           not null
#  password_digest        :string           not null
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class User < ApplicationRecord
  validates :email, presence: true

  has_many :transactions
  has_many :transaction_templates
  has_many :wallets
  has_many :categories

  after_create :create_initial_categories!

  has_secure_password

  class << self
    def with_reset_password_token(token)
      where.not(reset_password_sent_at: nil).find_by(reset_password_token: token.to_s)
    end
  end

  def create_initial_categories!
    transaction_type_id = TransactionType.find_by_name('Expense').id
    category_names = [
      'Food', 'Child Stuff', 'Necessity', 'Transportation', 'Clothes', 'Donation', 'Health',
      'House', 'Entertainment', 'Personal Stuff', 'Pet Stuff', 'Bank'
    ]

    category_names.each do |name|
      categories.where(name: name, transaction_type_id: transaction_type_id).first_or_create!
    end

    transaction_type_id = TransactionType.find_by_name('Income').id
    category_names = [
      'Salary', 'Bonus', 'Bank Interest', 'Others'
    ]

    category_names.each do |name|
      categories.where(name: name, transaction_type_id: transaction_type_id).first_or_create!
    end

    transaction_type_id = TransactionType.find_by_name('Borrow').id
    category_names = [
      'Borrowing', 'Debt Collecting', 'Repayment'
    ]

    category_names.each do |name|
      categories.where(name: name, transaction_type_id: transaction_type_id).first_or_create!
    end

    transaction_type_id = TransactionType.find_by_name('Lend').id
    category_names = [
      'Borrowing', 'Debt Collecting', 'Repayment'
    ]

    category_names.each do |name|
      categories.where(name: name, transaction_type_id: transaction_type_id).first_or_create!
    end
  end

  def generate_password_token!
    update_columns(
      reset_password_token: SecureRandom.hex(10),
      reset_password_sent_at: Time.now.utc
    )
  end

  def password_token_expired?
    (self.reset_password_sent_at + 4.hours) < Time.now.utc
  end

  def clear_password_token!
    update_columns(
      reset_password_token: nil,
      reset_password_sent_at: nil
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:error] = "Error- please try to create an account again."
      redirect_to new_user_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="max-w-md mx-auto w-full rounded-xl shadow-md overflow-hidden md:max-w-2xl mt-10 min-h-screen bg-white">
  <div class="md:flex flex flex-col">
    <div class="flex items-center p-8">
      <h3 class="block mt-1 text-lg leading-tight font-medium text-black">Hello <%= current_user.email %></h3>
      <div class="ml-4">
        <%= link_to 'Logout', logout_path, class: "bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded-md" %>
      </div>
    </div>
    <div class="bg-gray-200 p-4">
      <h3 class="text-xl font-semibold mb-4">Fitur</h3>
      <div class="flex flex-wrap">
        <div class="w-1/2 p-2">
          <%= link_to new_transaction_template_path, class: "flex items-center p-2 rounded-lg hover:bg-gray-300" do %>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mr-2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
            </svg>
            <span class="text-lg">Template Record</span>
          <% end %>
        </div>
        <div class="w-1/2 p-2">
          <%= link_to categories_path, class: "flex items-center p-2 rounded-lg hover:bg-gray-300" do %>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mr-2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M9 12h3.75M9 15h3.75M9 18h3.75m3 .75H18a2.25 2.25 0 002.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 00-1.123-.08m-5.801 0c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 00.75-.75 2.25 2.25 0 00-.1-.664m-5.8 0A2.251 2.251 0 0113.5 2.25H15c1.012 0 1.867.668 2.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m0 0H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V9.375c0-.621-.504-1.125-1.125-1.125H8.25zM6.75 12h.008v.008H6.75V12zm0 3h.008v.008H6.75V15zm0 3h.008v.008H6.75V18z" />
            </svg>
            <span class="text-lg">Categories</span>
          <% end %>
        </div>
        <div class="w-1/2 p-2">
          <%= link_to transactions_path(format: :pdf), class: "flex items-center p-2 rounded-lg hover:bg-gray-300" do %>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mr-2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
            </svg>
            <span class="text-lg">Export Data</span>
          <% end %>
        </div>
        <div class="w-1/2 p-2">
          <%= link_to transactions_chart_path, class: "flex items-center p-2 rounded-lg hover:bg-gray-300", remote: true do %>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mr-2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M3 13.125C3 12.504 3.504 12 4.125 12h2.25c.621 0 1.125.504 1.125 1.125v6.75C7.5 20.496 6.996 21 6.375 21h-2.25A1.125 1.125 0 013 19.875v-6.75zM9.75 8.625c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125v11.25c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 01-1.125-1.125V8.625zM16.5 4.125c0-.621.504-1.125 1.125-1.125h2.25C20.496 3 21 3.504 21 4.125v15.75c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 01-1.125-1.125V4.125z" />
            </svg>
            <span class="text-lg">Create Graph</span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :header do %>
  <%= render 'header', title: 'Profile' %>
<% end %>

<% content_for :navbar do %>
  <%= render 'navbar' %>
<% end %>

app/views/users/show.html.erb
<%= content_tag :h1, current_user.welcome %>
<%= link_to "Sign out", logout_path, method:"delete" %>