config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get 'register', to: 'registrations#new'
  post 'register', to: 'registrations#create'

  get 'chart', to: 'transactions#chart', as: 'transactions_chart'

  resources :users, only: [:new, :create, :index, :show]
  resources :wallets
  resources :categories
  resources :transactions
  resources :transaction_templates
  resources :passwords, only: %i[edit update], param: :token

  resource :reset_password, only: %i[new create]


  root "dashboard#index"
end

app/models/wallet.rb
# == Schema Information
#
# Table name: wallets
#
#  id                :bigint           not null, primary key
#  amount_in_decimal :integer          not null
#  description       :string
#  name              :string           not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  currency_id       :bigint           not null
#  user_id           :bigint           not null
#  wallet_type_id    :bigint           not null
#
# Indexes
#
#  index_wallets_on_currency_id     (currency_id)
#  index_wallets_on_user_id         (user_id)
#  index_wallets_on_wallet_type_id  (wallet_type_id)
#
# Foreign Keys
#
#  fk_rails_...  (currency_id => currencies.id)
#  fk_rails_...  (user_id => users.id)
#  fk_rails_...  (wallet_type_id => wallet_types.id)
#
class Wallet < ApplicationRecord
  belongs_to :user
  belongs_to :wallet_type
  belongs_to :currency

  has_many :transactions, dependent: :destroy
  has_many :transaction_templates, dependent: :destroy
  has_many :related_transactions, class_name: 'Transaction', foreign_key: :source_wallet_id, dependent: :destroy

  validates :name, presence: true, length: { minimum: 3 }
  validates :amount, presence: true, numericality: { greater_than_or_eq: 0 }

  def amount=(value)
    write_attribute(:amount_in_decimal, value.to_f * 100)
  end

  def amount
    read_attribute(:amount_in_decimal).to_f / 100.0
  end

  def self.ransackable_attributes(auth_object = nil)
    ['name']
  end

  def sync_transactions!
    update!(amount_in_decimal: transactions.order(transaction_at: :desc).pluck(:amount_in_decimal).sum)
  end
end

app/models/wallet_type.rb
# == Schema Information
#
# Table name: wallet_types
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class WalletType < ApplicationRecord
  has_many :wallets
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  before_action :current_wallet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @q = Wallet.where(user_id: current_user).ransack(params[:q])
    @wallets = @q.result(distinct: true)
  end

  def show
  end

  def edit
  end

  def update
    @wallet.update(wallet_params)

    redirect_to wallets_path(@wallet)
  end

  def new
    @wallet = Wallet.new
  end

  def create
    @wallet = Wallet.new(wallet_params)

    if @wallet.save
      redirect_to wallets_path
    else
      render :new, status: 422
    end
  end

  def destroy
    @wallet.destroy

    redirect_to wallets_path
  end

  private
  def wallet_params
    params.require(:wallet).permit(
      :name, :wallet_type_id, :currency_id, :amount, :description
    ).merge(user_id: current_user.id)
  end

  def current_wallet
    @wallet = Wallet.find(params[:id])
  end
end

app/helpers/wallets_helper.rb
module WalletsHelper
  def wallet_select_options
    Wallet.where(user_id: current_user.id).map { |w| [w.name, w.id] }
  end

  def current_user_wallet
    @current_user_wallet = Wallet.where(user_id: current_user)
  end

  def current_total_balance
    @current_total_balance = current_user_wallet.all.sum(&:amount)
  end
end

app/views/wallets/_form.html.erb
<%= render 'errors', errors: @wallet.errors.full_messages %>
<%= form_with model: @wallet, class: "space-y-6" do |form| %>
  <div>
    <%= form.label :name, class: "text-sm font-medium text-gray-700 block" %>
      <div class="mt-1">
        <%= form.text_field :name, class: "text-sm font-normal px-3 py-2 mb-2 text-slate-700 border
          shadow rounded w-full placeholder: text-slate-700 focus:outline-none focus:ring-l
          focus:ring-green-500 focus:border-green-500 invalid:text-red-700 invalid:focus:ring-red-700
          invalid:focus:border-red-700" %>
      </div>
    </div>
    <div>
      <%= form.label :wallet_type_id, class: "text-sm font-medium text-gray-700 block"%>
      <div class="mt-1 ">
        <%= form.select :wallet_type_id, wallet_type_select_options, {}, class: "text-sm font-normal
          px-3 py-2 mb-2 text-slate-700 border shadow rounded w-full placeholder: text-slate-700
          focus:outline-none focus:ring-l focus:ring-green-500 focus:border-green-500 invalid:text-red-700
          invalid:focus:ring-red-700 invalid:focus:border-red-700" %>
      </div>
    </div>
      <div>
        <%= form.label :currency_id, class: "text-sm font-medium text-gray-700 block"%>
        <div class="mt-1 ">
          <%= form.select :currency_id, currency_select_options, {}, class: "text-sm font-normal px-3
            py-2 mb-2 text-slate-700 border shadow rounded w-full placeholder: text-slate-700 focus:outline-none
            focus:ring-l focus:ring-green-500 focus:border-green-500 invalid:text-red-700 invalid:focus:ring-red-700
            invalid:focus:border-red-700" %>
        </div>
    </div>
    <div>
      <%= form.label :amount, class: "text-sm font-medium text-gray-700 block"%>
      <div class="mt-1">
        <%= form.number_field :amount, class: "text-sm font-normal px-3 py-2 mb-2 text-slate-700
          border shadow rounded w-full placeholder: text-slate-700 focus:outline-none focus:ring-l
          focus:ring-green-500 focus:border-green-500 invalid:text-red-700 invalid:focus:ring-red-700
          invalid:focus:border-red-700" %>
      </div>
    </div>
    <div>
      <%= form.label :description, class: "text-sm font-medium text-gray-700 block"%>
      <div class="mt-1">
        <%= form.text_field :description, class: "text-sm font-normal px-3 py-2 mb-2 text-slate-700
          border shadow rounded w-full placeholder: text-slate-700 focus:outline-none focus:ring-l
          focus:ring-green-500 focus:border-green-500 invalid:text-red-700 invalid:focus:ring-red-700
          invalid:focus:border-red-700" %>
      </div>
    </div>
    <div>
      <%= form.submit class: "w-full flex justify-center mt-4 py-2 px-4 border border-transparent
        rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 focus:outline-none
        focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
    </div>
<% end %>

app/views/wallets/edit.html.erb
<div class="min-h-screen bg-bgColor flex flex-col items-center justify-center px-4 sm:px-6 lg:px-8 ">
  <div class="bg-white p-8 rounded-lg shadow-md max-w-md w-full">
    <h2 class="font-bold text-2xl ">Edit Wallet</h2>
    <%= render partial: 'form' %>
  </div>
</div>
<% content_for :navbar do %>
  <%= render 'navbar' %>
<% end %>

app/views/wallets/index.html.erb
<div class="max-w-md mx-auto w-full rounded-xl shadow-md overflow-hidden md:max-w-2xl mt-28 min-h-screen bg-white">
  <div class="md:flex flex flex-col">
    <% @wallets.each do |wallet| %>
      <div class="border-b-2 flex items-center bg-white">
        <div class="md:flex-shrink-0 mr-6">
          <img class="object-cover h-12 w-12 sm:h-16 sm:w-16 rounded-full max-w-none ml-4" src="https://source.unsplash.com/random" alt="Random Image">
        </div>
        <div class="p-8 flex justify-between items-center w-full">
          <div>
            <h3 class="block mt-1 text-lg leading-tight font-medium text-black"><%= wallet.name %></h3>
            <p class="mt-2 text-gray-500"><%= number_to_currency(wallet.amount) %></p>
          </div>
          <div>
            <button onclick="toggleOverlay('<%= wallet.id %>')">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 6.75a.75.75 0 110-1.5.75.75 0 010 1.5zM12 12.75a.75.75 0 110-1.5.75.75 0 010 1.5zM12 18.75a.75.75 0 110-1.5.75.75 0 010 1.5z" />
              </svg>
            </button>
          </div>
        </div>
      </div>
      <div id="overlay_<%= wallet.id %>" class="fixed inset-0 bg-gray-900 bg-opacity-50 flex items-center justify-center hidden">
        <div class="bg-white rounded-lg shadow-lg p-8 relative">
          <div class="flex justify-end">
            <%= link_to 'Remove', wallet_path(wallet), data: { turbo_method: :delete, confirm: 'Are you sure?' }, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded-md shadow mr-2 mb-2" %>
            <%= link_to 'Edit', edit_wallet_path(wallet), class: "border border-gray-300 text-gray-800 font-bold py-2 px-4 rounded-md shadow mr-2 mb-2" %>
          </div>
          <div class="flex justify-center">
            <button onclick="toggleOverlay('<%= wallet.id %>')" class= "text-gray-400 hover:text-gray-600 font-bold py-2 px-4 rounded-md shadow mb-2 w-full">
              Cancel
            </button>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="flex w-full justify-end">
    <%= link_to new_wallet_path, class: "bg-blue-500 hover:bg-blue-600 text-white font-bold p-4 rounded-full fixed drop-shadow-xl" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
      </svg>
    <% end %>
  </div>
</div>

<script>
  function toggleOverlay(walletId) {
    const overlay = document.getElementById(`overlay_${walletId}`);
    overlay.classList.toggle('hidden');
  }
</script>

<% content_for :header do %>
  <%= render 'header', title: 'Wallet', child_links: [['Account', wallets_path], ['Savings', root_path], ['Accumulate', root_path]] %>
  <p class="text-center">Total Amount: <%= number_to_currency(current_total_balance) %></p>
<% end %>

<% content_for :navbar do %>
  <%= render 'navbar' %>
<% end %>

app/views/wallets/new.html.erb
<div class="min-h-screen bg-bgColor flex flex-col items-center justify-center px-4 sm:px-6 lg:px-8">
  <div class="bg-white p-8 rounded-lg shadow-md max-w-md w-full">
    <div class="text-center">
      <h1 class="text-2xl font-bold text-gray-800 mb-4">Wallet Baru</h1>
    </div>
    <%= render partial: 'form' %>
  </div>
</div>

app/views/wallets/show.html.erb
<div class="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden md:max-w-2xl ">
  <div class="md:flex flex flex-col">
    <div class="border-b-2 flex items-center">
      <div class="md:flex-shrink-0 mr-6 ">
        <img class="object-cover h-12 w-12 sm:h-16 sm:w-16 rounded-full max-w-none ml-4" src="https://source.unsplash.com/random" alt="Random Image">
      </div>
      <div class="p-8">
        <h3 class="block mt-1 text-lg leading-tight font-medium text-black"><%= @wallet.name %></h3>
        <div class="mt-2">
          <p class="text-gray-500"><%= number_to_currency(@wallet.amount) %></p>
          <p class="text-gray-500"><%= wallet_type_name_translate(@wallet.wallet_type) %></p>
          <p class="text-gray-500"><%= @wallet.description %></p>
          <div class="flex flex-row justify-between space-x-6 mt-4">
            <%= link_to 'Remove', @wallet, data: { turbo_method: :delete, confirm: 'Are you sure?' }, class:"bg-gradient-to-r from-red-500 to-red-700 hover:from-red-700 hover:to-red-900 text-white font-bold py-2 px-4 rounded-md shadow-lg transition duration-500 ease-in-out transform hover:-translate-y-1 hover:scale-110" %>
            <%= link_to 'Edit', edit_wallet_path(@wallet), class: "border border-gray-100 text-gray-800 font-bold py-2 px-4 rounded-md shadow transition duration-500 ease-in-out transform hover:-translate-y-1 hover:scale-110" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>