config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get 'register', to: 'registrations#new'
  post 'register', to: 'registrations#create'

  get 'chart', to: 'transactions#chart', as: 'transactions_chart'

  resources :users, only: [:new, :create, :index, :show]
  resources :wallets
  resources :categories
  resources :transactions
  resources :transaction_templates
  resources :passwords, only: %i[edit update], param: :token

  resource :reset_password, only: %i[new create]


  root "dashboard#index"
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id                  :bigint           not null, primary key
#  description         :string
#  name                :string           not null
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  transaction_type_id :bigint           not null
#  user_id             :bigint           not null
#
# Indexes
#
#  index_categories_on_transaction_type_id  (transaction_type_id)
#  index_categories_on_user_id              (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (transaction_type_id => transaction_types.id)
#  fk_rails_...  (user_id => users.id)
#
class Category < ApplicationRecord
  has_many :transactions
  has_many :transaction_templates
  has_many :transaction_types

  belongs_to :user

  validates :name, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ['name']
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :current_category, only: [:show, :edit, :update, :destroy]

  def index
    @q = Category.where(user_id: current_user).ransack(params[:q])
    @categories = @q.result(distinct: true)

    if params[:back_button].present?
      redirect_to categories_path
    end
  end

  def show
  end

  def edit
  end

  def update
    @category.update(category_params)

    redirect_to categories_path(@category)
  end

  def new
    @category = Category.new
  end


  def create
    @category = Category.create(category_params)

    if @category.save
      redirect_to categories_path
    else
      render :new, status: 422
    end
  end

  def destroy
    @category.destroy

    redirect_to categories_path
  end

  private
  def category_params
    params.require(:category).permit(:name, :description)
  end

  def current_category
    @category = Category.find(params[:id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def category_select_options(user_id, transaction_type_id = nil)
    transaction_type_id = TransactionType.find_by_name('Expense').id if transaction_type_id.blank?
    Category.where(user_id: user_id, transaction_type_id: transaction_type_id).map { |c| [(c.name), c.id] }
  end
end

app/views/categories/destroy.html.erb
<h1>TransactionCategories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<div class="min-h-screen bg-bgColor flex flex-col items-center justify-center px-4 sm:px-6 lg:px-8">
  <div class="bg-white p-8 rounded-lg shadow-md max-w-md w-full">
    <h2 class="font-bold text-2xl ">Category</h2>
    <%= form_with model: @category, class: "space-y-6" do |form| %>
      <div>
        <%= form.label :name, class: "text-sm font-medium text-gray-700 block"%>
        <div class="mt-1">
          <%= form.text_field :name, class: "text-sm font-normal px-3 py-2 mb-2 text-slate-700 border shadow rounded w-full placeholder: text-slate-700 focus:outline-none focus:ring-l focus:ring-green-500 focus:border-green-500 invalid:text-red-700 invalid:focus:ring-red-700 invalid:focus:border-red-700" %>
        </div>
      </div>
      <div>
        <% if @category.errors.full_messages.present? %>
          <% @category.errors.full_messages.each do |error| %>
            <span class="text-red-500 my-3"><%= error %></span>
          <% end %>
        <% end %>
      </div>
      <div>
        <%= form.label :description, class: "text-sm font-medium text-gray-700 block"%>
        <div class="mt-1">
          <%= form.text_field :description, class: "text-sm font-normal px-3 py-2 mb-2 text-slate-700 border shadow rounded w-full placeholder: text-slate-700 focus:outline-none focus:ring-l focus:ring-green-500 focus:border-green-500 invalid:text-red-700 invalid:focus:ring-red-700 invalid:focus:border-red-700" %>
        </div>
      </div>
      <div>
        <%= form.submit class: "w-full flex justify-center mt-4 py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/index.html.erb
<% content_for :header do %>
  <%= render 'header', title: 'Category'%>
<% end %>

<% content_for :navbar do %>
  <%= render 'navbar' %>
<% end %>

<section class="category-name bg-white min-h-screen h-full">
  <ul class="pt-24">
    <!-- <button class="w-10 h-10 z-0 p-2 rounded-full bg-red-400 border-b-2 border-gray-500 sticky top-[800px] left-[700px]">A</button> -->
    <%= 20.times do %>
      <li class="flex justify-between border border-gray-300 items-center p-4">
        <img class="object-cover h-12 w-12 rounded-full" src="https://source.unsplash.com/random" alt="Random Image">
        <span>some text</span>
        <button>option</button>
      </li>
    <% end %>
  </ul>
  <ul>
  </ul>

</section>
<!--
<div class="nav-mobile max-w-md mx-auto w-full shadow-md overflow-hidden md:max-w-2xl my-16 min-h-screen bg-white ">
  <div class="parent-list md:flex flex flex-col pb-[100px]">
    <div class="button-biru flex z-10 rounded-full">
      <%= link_to new_category_path, class: "bg-blue-500 hover:bg-blue-600 text-white font-bold p-4 rounded-full drop-shadow-xl" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
        </svg>
      <% end %>
    </div>
    <% @categories.each do |category| %>
    <div class="border-b-2 flex items-center bg-white">
      <div class="md:flex-shrink-0 mr-6">
        <img class="object-cover h-12 w-12 sm:h-16 sm:w-16 rounded-full max-w-none ml-4" src="https://source.unsplash.com/random" alt="Random Image">
      </div>
      <div class="p-8 flex justify-between items-center w-full">
        <div>
          <h3 class="block mt-1 text-lg leading-tight font-medium text-black"><%= category.name %></h3>
          <p class="mt-2 text-gray-500"><%= category.description %></p>
        </div>
        <div>
          <button onclick="toggleOverlay('<%= category.id %>')">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M12 6.75a.75.75 0 110-1.5.75.75 0 010 1.5zM12 12.75a.75.75 0 110-1.5.75.75 0 010 1.5zM12 18.75a.75.75 0 110-1.5.75.75 0 010 1.5z" />
            </svg>
          </button>
        </div>
      </div>
      <div id="overlay_<%= category.id %>" class="fixed inset-0 bg-gray-900 bg-opacity-50 flex items-center justify-center hidden">
        <div class="bg-white rounded-lg shadow-lg p-8 relative">
          <div class="flex justify-end">
            <%= link_to 'Remove', category_path(category), data: { turbo_method: :delete, confirm: 'Are you sure?' }, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded-md shadow mr-2 mb-2" %>
            <%= link_to 'Edit', edit_category_path(category), class: "border border-gray-300 text-gray-800 font-bold py-2 px-4 rounded-md shadow mr-2 mb-2" %>
          </div>
          <div class="flex justify-center">
            <button onclick="toggleOverlay('<%= category.id %>')" class= "text-gray-400 hover:text-gray-600 font-bold py-2 px-4 rounded-md shadow mb-2 w-full">
              Cancel
            </button>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    <div class="button-biru flex z-10 rounded-full">
      <%= link_to new_category_path, class: "bg-blue-500 hover:bg-blue-600 text-white font-bold p-4 rounded-full drop-shadow-xl" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
        </svg>
      <% end %>
    </div>
  </div>
</div> -->

<script>
  function toggleOverlay(categoryId) {
    const overlay = document.getElementById(`overlay_${categoryId}`);
    overlay.classList.toggle('hidden');
  }
</script>

app/views/categories/new.html.erb
<ul>
  <% @category.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
</ul>

<div class="min-h-screen bg-bgColor flex flex-col items-center justify-center px-4 sm:px-6 lg:px-8">
  <div class="bg-white p-8 rounded-lg shadow-md max-w-md w-full">

    <div class="text-center">
      <h1 class="text-2xl font-bold text-gray-800 mb-4">Create Transaction Category</h1>
      <p class="text-gray-600 mb-8">Please enter your details.</p>
    </div>
    <%= form_with model: @category, class: "space-y-6" do |form| %>
      <div>
        <%= form.label :name, class: "text-sm font-medium text-gray-700 block"%>
        <div class="mt-1">
          <%= form.text_field :name, class: "text-sm px-3 py-2 mb-2 text-slate-700 border shadow rounded-md w-full focus:outline-none focus:ring-l focus:ring-green-500 focus:border-green-500 invalid:text-red-700 invalid:focus:ring-red-700 invalid:focus:border-red-700" %>
        </div>
      </div>
      <div>
        <% if @category.errors.full_messages.present? %>
          <% @category.errors.full_messages.each do |error| %>
            <span class="text-red-500 my-3"><%= error %></span>
          <% end %>
        <% end %>
      </div>
      <div>
        <%= form.label :description, class: "text-sm font-medium text-gray-700 block"%>
        <div class="mt-1">
          <%= form.text_area :description, class: "resize-none w-full h-32 px-3 py-2 text-sm border shadow rounded-md focus:outline-none focus:ring-1 focus:ring-green-500 focus:border-green-500 invalid:text-red-700 invalid:focus:ring-red-700 invalid:focus:border-red-700" %>
        </div>
      </div>
      <div>
        <%= form.submit "Create", class: "w-full flex justify-center mt-4 py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden md:max-w-2xl ">
  <div class="md:flex flex flex-col">
    <div class="border-b-2 flex items-center">
      <div class="md:flex-shrink-0 mr-6 ">
        <img class="object-cover h-12 w-12 sm:h-16 sm:w-16 rounded-full max-w-none ml-4" src="https://source.unsplash.com/random" alt="Random Image">
      </div>
      <div class="p-8">
        <h3 class="block mt-1 text-lg leading-tight font-medium text-black"><%= @category.name %></h3>
        <div class="mt-2">
          <p class="text-gray-500"><%= @category.description %></p>
          <div class="flex flex-row justify-between space-x-6 mt-4">
            <%= link_to 'Remove', @category	, method: :delete, class:"bg-gradient-to-r from-red-500 to-red-700 hover:from-red-700 hover:to-red-900 text-white font-bold py-2 px-4 rounded-md shadow-lg" %>
            <%= button_to 'Edit', edit_category_path, method: :get, class: "border border-gray-100 text-gray-800 font-bold py-2 px-4 rounded-md shadow"%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>