config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get 'register', to: 'registrations#new'
  post 'register', to: 'registrations#create'

  get 'chart', to: 'transactions#chart', as: 'transactions_chart'

  resources :users, only: [:new, :create, :index, :show]
  resources :wallets
  resources :categories
  resources :transactions
  resources :transaction_templates
  resources :passwords, only: %i[edit update], param: :token

  resource :reset_password, only: %i[new create]


  root "dashboard#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :user_signed_in?

  def authenticate_user!
    redirect_to login_path if current_user.blank?
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session.include?(:user_id) && session[:user_id]
  end

  def user_signed_in?
    current_user.present?
  end

  def redirect_if_user_authenticated
    if user_signed_in?
      redirect_to root_path, notice: 'Already Logged In'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_errors.html.erb
<% if errors.present? %>
  <div class="flex flex-row bg-red-50 rounded-xl items-stretch">
    <div class="flex px-4 bg-red-200 rounded-md items-center">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="#F87171" class="w-8 h-8">
        <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z" />
      </svg>
    </div>
    <div class= "p-4 mb-4 text-sm text-red-800 rounded-lg text-red-400" >
      <p><strong>Gagal Submit Data</strong></p>
      <ul>
        <% errors.each do |error| %>
          <li ><%= error %>.</li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/application/_header.html.erb
<nav class="fixed z-10 bg-blue-500 w-[425px] h-50 top-0 left-1/2 transform -translate-x-1/2">
  <div class="mx-auto px-4 py-2 max-w-7xl sm:px-6 lg:px-8">
    <div class="flex flex-col items-center justify-between">
      <% if title == 'Home' && user_signed_in? %>
        <%= title %>
        <p>Hi <%= current_user.email.split('@').first %> </p>
      <% end %>
      <% if title == 'Wallet' %>
       <%= title %>
        <form>
          <div class="flex flex-row items-center">
            <%= search_form_for @q do |f| %>
              <label for="search" class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Search</label>
              <div class="relative">
                <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                  <svg aria-hidden="true" class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
                </div>
                <%= f.search_field :name_cont, id: "search", class: "block w-full p-4 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500", placeholder: "Search", required: true %>
                <button type="submit" class="text-white absolute right-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 ">Search</button>
              </div>
            <% end %>
          </div>
        </form>
      <% end %>
    <% if title == 'Category' %>
      <div class="flex flex-row items-center">
        <% if params[:q].present? %>
          <%= link_to categories_path(back_button: true), class: "text-white mr-2" do %>
            <svg class="w-6 h-6 font-semibold" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <path d="M10 19l-7-7m0 0l7-7m-7 7h18"></path>
            </svg>
          <% end %>
        <% end %>
        <!-- <%= title %> -->
        <form>
          <div class="flex flex-row items-center">
            <%= search_form_for @q do |f| %>
              <label for="search" class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Search</label>
              <div class="relative">
                <%= f.search_field :name_cont, id: "search", class: "block w-full p-4 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500", placeholder: "Search", required: true %>
                <button type="submit" class="text-white absolute right-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2">Search</button>
              </div>
            <% end %>
          </div>
        </form>
      </div>
    <% end %>
      <% if title == 'Transaction' %>
        <div class="flex flex-row items-center">
          <%= title %>
        </div>
      <% end %>
      <% if title == 'Profile' %>
        <div class="flex flex-row items-center">
          <%= title %>
        </div>
      <% end %>
      <% if defined?(child_links) %>
        <div class="flex flex-row border-b border-gray-200 dark:border-gray-700">
          <ul class="flex justify-center text-sm font-medium text-center">
            <% child_links.each do |child_link| %>
              <li class='mr-2'>
                <%= link_to child_link[0], child_link[1],  class: 'inline-block p-4 border-b-2 border-transparent rounded-t-lg hover:text-white hover:border-gray-300' %>
              </li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/application/_navbar.html.erb
<div class="fixed z-10 bottom-0 left-0 right-0 mx-auto w-[425px] max-w-lg bg-white shadow-lg rounded-t-lg z-10">
  <button class="w-10 h-10 z-0 p-2 rounded-full bg-red-400 border-b-2 border-gray-500 sticky top-[800px] left-[700px]">A</button>
  <div class="flex justify-around py-2">
    <%= link_to root_path, class: "flex flex-col items-center text-gray-500 hover:text-black" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mb-2 mx-auto">
        <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
      </svg>
      <p class="text-xs font-medium">Home</p>
    <% end %>
    <%= link_to wallets_path, class: "flex flex-col items-center text-gray-500 hover:text-black" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewB ox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mb-2 mx-auto">
        <path stroke-linecap="round" stroke-linejoin="round" d="M21 12a2.25 2.25 0 00-2.25-2.25H15a3 3 0 11-6 0H5.25A2.25 2.25 0 003 12m18 0v6a2.25 2.25 0 01-2.25 2.25H5.25A2.25 2.25 0 013 18v-6m18 0V9M3 12V9m18 0a2.25 2.25 0 00-2.25-2.25H5.25A2.25 2.25 0 003 9m18 0V6a2.25 2.25 0 00-2.25-2.25H5.25A2.25 2.25 0 003 6v3" />
      </svg>
      <p class="text-xs font-medium">Wallet Account</p>
    <% end %>
    <%= link_to new_transaction_path, class: "bg-green-500 hover:bg-green-600 focus:outline-none w-16 h-16 rounded-full flex items-center justify-center -mt-8" do %>
      <svg class="h-6 w-6 text-white" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M12 5V19" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
        <path d="M5 12H19" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>
    <% end %>
    <%= link_to transactions_path, class: "flex flex-col items-center text-gray-500 hover:text-black" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mb-2 mx-auto">
        <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 18.75a60.07 60.07 0 0115.797 2.101c.727.198 1.453-.342 1.453-1.096V18.75M3.75 4.5v.75A.75.75 0 013 6h-.75m0 0v-.375c0-.621.504-1.125 1.125-1.125H20.25M2.25 6v9m18-10.5v.75c0 .414.336.75.75.75h.75m-1.5-1.5h.375c.621 0 1.125.504 1.125 1.125v9.75c0 .621-.504 1.125-1.125 1.125h-.375m1.5-1.5H21a.75.75 0 00-.75.75v.75m0 0H3.75m0 0h-.375a1.125 1.125 0 01-1.125-1.125V15m1.5 1.5v-.75A.75.75 0 003 15h-.75M15 10.5a3 3 0 11-6 0 3 3 0 016 0zm3 0h.008v.008H18V10.5zm-12 0h.008v.008H6V10.5z" />
      </svg>
      <p class="text-xs font-medium">Transaction</p>
    <% end %>
    <%= link_to users_path, class: "flex flex-col items-center text-gray-500 hover:text-black" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mb-2 mx-auto">
        <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
      </svg>
      <p class="text-xs font-medium">Profile</p>
    <% end %>
  </div>
</div>